### ISSUE TITLE
Can you import the vector Behavior to escape pod 

### ISSUE THREAD

**Issue by NerdsCorp** [cyb3rdog/Cyb3rVector#10]
Is there any way after making a behavior with blocky to import it permanently to escape pod.

**Comment by cyb3rdog** [comment]
Hi, 

not yet, but yes, i am still planning to release this feature. 
See the [discussions here](https://github.com/cyb3rdog/Cyb3rVector/discussions/8) 

Many thanks for your interrest, and stay tuned!

**Comment by cyb3rdog** [comment]
Closing, as it is not an issue. 
Requested feature is already on the roadmap
