### ISSUE TITLE
"Escape Pod" section not showing up in block categories

### ISSUE THREAD

**Issue by xanathon** [cyb3rdog/Cyb3rVector#19]
I have successfully connected the portable version 0.9.57 of Cyb3rvector to Escape Pod (1.0.x). However, in your Youtube video I see an "Escape Pod" entry in the block categories list to the left. I am missing that. Why?

Thanks in advance.

**Comment by cyb3rdog** [comment]
Hi Xanathon, 

that yt video is honestly quite old and initally was not meant to be actually public, so i should shoot the new.
In the latest app version, all the related blocks will appear in "voice commands" category, where I actually attempted to simplify this for everyone as much as possible:
- So in case of regular production vector the OnVoiceCommand block receives all the voice commands from both the "wake word end" and "on user intent" so the end users don't need to care about the control state. 
- For an escapepod robots with escapepod extension deployed, that very same block additionally receives also the events from ep, regardless of whether they're done manually from Ui, dynamically from app, and regardless of whether they're marked as extension intents or not.

The goal here was simple, to unify all the backend voice command "sources" into one block.

Hope this helps,
Cheers,
cyb3rdog

**Comment by xanathon** [comment]
Thanks.
